# fly.toml app configuration file generated for bot-northstar on 2024-02-01T15:18:11-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bot-northstar'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 8080
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
